### ISSUE TITLE
Refreshing a token does not work based on the proposed configuration

### ISSUE THREAD

**Issue by korneliuscode** [microsoftgraph/msgraph-training-nodeexpressapp#22] opened 2019-12-30 16:56 UTC
I ran into an issue with the proposed configuration. This is the suggested config:
```
OAUTH_AUTHORITY=https://login.microsoftonline.com/common
OAUTH_ID_METADATA=/v2.0/.well-known/openid-configuration
OAUTH_AUTHORIZE_ENDPOINT=/oauth2/v2.0/authorize
OAUTH_TOKEN_ENDPOINT=/oauth2/v2.0/token
```
wreck inside simple-oauth2 uses [Url.URL][1] to combine `OAUTH_AUTHORITY` with `OAUTH_TOKEN_ENDPOINT` which results in `https://login.microsoftonline.com/oauth2/v2.0/token` and therefore loses `common`. This results in a `404`.

I changed the config slightly and removed the leading slashes from the relative paths and added a trailing slash to the base URL.
```
OAUTH_AUTHORITY=https://login.microsoftonline.com/common/
OAUTH_ID_METADATA=/v2.0/.well-known/openid-configuration
OAUTH_AUTHORIZE_ENDPOINT=oauth2/v2.0/authorize
OAUTH_TOKEN_ENDPOINT=oauth2/v2.0/token
```
So that `OAUTH_TOKEN_ENDPOINT` is relative. I have not figured why it worked for authorize though, but still works.

  [1]: https://nodejs.org/api/url.html#url_constructor_new_url_input_base

**Comment by jasonjoh** [comment] 2020-01-06 16:20
Interesting. I haven't run into this. What version of simple-oauth2 and wreck are you using?

**Comment by korneliuscode** [comment] 2020-01-07 10:13
It's "simple-oauth2": 3.1.0" and "hapi/wreck": 15.1.0

**Comment by jasonjoh** [comment] 2020-01-07 13:54
Hmm. Same here. What OS are you running on?

**Comment by korneliuscode** [comment] 2020-01-07 15:53
My devbox is windows 10. No production yet.

**Comment by jasonjoh** [comment] 2020-01-13 13:42
I was finally able to reproduce this. The reason authorize works is because the app uses passport for that, not simple-oauth2.

Thanks for reporting, I'll get a fix for this shortly.

**Closed** 2020-01-13 13:46 UTC
