### ISSUE TITLE
Error 404 when trying to get the app from the Quick Start web page

### ISSUE THREAD

**Issue by mengstr** [microsoftgraph/msgraph-training-nodeexpressapp#56] opened 2020-11-21 12:50 UTC
After selecting node.js as the platform on [https://developer.microsoft.com/en-us/graph/quick-start](url), getting the App ID and Secret, pasting the copied secret into the form field on the page the next step is to download the code sample.

Clicking the button there I only get to a 404-page at the URL https://codeload.github.com/microsoftgraph/msgraph-training-nodeexpressapp/zip/master

<img width="480" alt="Screen Shot 2020-11-21 at 1 45 05 PM" src="https://user-images.githubusercontent.com/325326/99877672-0591de80-2c00-11eb-9da4-4d61d89e81ac.png">

Not sure if this is an error caused by github or your url is wrong - but anyways, it doesn't work as intended.

**Comment by jasonjoh** [comment] 2020-11-30 17:49
Are you using Safari by chance? 

I believe this is caused by the updates changing the default branch from master to main. I'll let the quick-start devs know about this change so they can update across the board.

**Comment by SmallRoomLabs** [comment] 2020-11-30 20:28
Yes, I wnet over to Safari from Chrome about a year ago in the hopes of a slightly smaller memory footprint - not sure if it's in vain or not but it feels kinda good to use native apps ;-)

**Comment by jasonjoh** [comment] 2020-12-11 18:46
Yeah the quick start tool just redirects to GitHub in Safari. In Chrome it should work as expected.

**Comment by boillodmanuel** [comment] 2021-02-03 17:36
Reproduced with Opera browser. I confirm that it works with Chrome

**Comment by jasonjoh** [comment] 2021-06-29 19:46
I have a fix for this in process with the quickstart tool.

**Comment by dshilkret** [comment] 2021-06-30 14:42
When running this example app. I receive the following error related to "valueOf()". Is this deprecated?

Cannot read property 'valueOf' of undefined
TypeError: Cannot read property 'valueOf' of undefined
    at C:\Teams Integration\graph\node\v1\graph-tutorial\routes\calendar.js:31:44
    at handleReturn (C:\Teams Integration\graph\node\v1\graph-tutorial\node_modules\express-promise-router\lib\express-promise-router.js:24:23)
    at C:\Teams Integration\graph\node\v1\graph-tutorial\node_modules\express-promise-router\lib\express-promise-router.js:64:7
    at handleReturn (C:\Teams Integration\graph\node\v1\graph-tutorial\node_modules\express-promise-router\lib\express-promise-router.js:24:23)
    at C:\Teams Integration\graph\node\v1\graph-tutorial\node_modules\express-promise-router\lib\express-promise-router.js:64:7
    at Layer.handle [as handle_request] (C:\Teams Integration\graph\node\v1\graph-tutorial\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\Teams Integration\graph\node\v1\graph-tutorial\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (C:\Teams Integration\graph\node\v1\graph-tutorial\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (C:\Teams Integration\graph\node\v1\graph-tutorial\node_modules\express\lib\router\layer.js:95:5)
    at C:\Teams Integration\graph\node\v1\graph-tutorial\node_modules\express\lib\router\index.js:281:22

**Comment by jasonjoh** [comment] 2021-06-30 16:46
No, it is not deprecated. `valueOf` is called on a time zone object after calling `iana.findIana(user.timeZone)[0];`. It may be that your user account doesn't have a timezone set in their mailbox settings. You can check this at https://outlook.office.com/mail/options/general/timeAndLanguage

**Closed** 2022-01-18 14:07 UTC
Labels: out of scope
